name: Deploy WebApplication1 to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Restore NuGet packages
        run: dotnet restore ${{ env.solution }}

      - name: Build and Publish WebApplication1
        run: dotnet publish '**/WebApplication1.csproj' --configuration ${{ env.buildConfiguration }} --output ${{ github.workspace }}/WebApplication1

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: ${{ github.workspace }}/WebApplication1

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: drop

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          package: '${{ github.workspace }}/WebApplication1'
          slot-name: 'production'
          virtual-application: 'WebApplication1'
          enable-custom-deployment: true
          deployment-type: 'webDeploy'
          app-settings: '-SCM_DO_BUILD_DURING_DEPLOYMENT false'
