name: Deploy WebApplication1 to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish WebApplication1
        run: dotnet publish WebApplication1/WebApplication1.csproj -c Release -o ${{ github.workspace }}/publish

      - name: Prepare Deployment Structure
        run: |
          # Create the correct directory structure
          mkdir -p ${{ github.workspace }}/deploy/WebApplication1
          
          # Copy all published files to the WebApplication1 directory
          Copy-Item -Path "${{ github.workspace }}/publish/*" -Destination "${{ github.workspace }}/deploy/WebApplication1" -Recurse
          
          # Copy web.config to the WebApplication1 directory
          Copy-Item -Path "WebApplication1/web.config" -Destination "${{ github.workspace }}/deploy/WebApplication1/web.config" -Force

      - name: Create ZIP Package
        run: Compress-Archive -Path ${{ github.workspace }}/deploy/* -DestinationPath ${{ github.workspace }}/deploy.zip

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}/deploy.zip

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build
    environment: production
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy WebApplication1 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          package: ${{ github.workspace }}/deploy.zip
          respect-virtual-application: true
