name: Deploy WebApplication1 to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Publish WebApplication1
        run: |
          # Show current directory structure before publish
          Write-Host "Directory structure before publish:"
          Get-ChildItem -Path ${{ github.workspace }} -Recurse -Depth 2
          
          # Create the publish directory
          $publishPath = "${{ github.workspace }}/publish"
          New-Item -ItemType Directory -Force -Path $publishPath
          
          # Publish the application
          dotnet publish WebApplication1/WebApplication1.csproj -c Release -o "$publishPath"
          
          # Show directory structure after publish
          Write-Host "`nDirectory structure after publish:"
          Get-ChildItem -Path $publishPath -Recurse -Depth 2
      
      - name: Add deployment config
        run: |
          Add-Content -Path "${{ github.workspace }}/publish/.deployment" -Value @"
          [config]
          SCM_DO_BUILD_DURING_DEPLOYMENT=true
          WEBSITE_RUN_FROM_PACKAGE=0
          "@
      
      - name: Create ZIP Package
        run: |
          # Create a temporary directory for files to zip
          $tempDir = "${{ github.workspace }}/temp_publish"
          New-Item -ItemType Directory -Force -Path $tempDir
          
          # Copy published files - simplified path
          Copy-Item "${{ github.workspace }}/publish/*" -Destination "$tempDir" -Recurse
          
          # Create the zip from the temporary directory
          Compress-Archive -Path "$tempDir/*" -DestinationPath "${{ github.workspace }}/WebApplication1.zip" -Force
  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Debug Directory Structure
        run: |
          Write-Host "Current workspace directory:"
          Get-Location
          Write-Host "`nListing workspace contents:"
          Get-ChildItem -Path ${{ github.workspace }} -Recurse -Depth 2
          Write-Host "`nListing publish directory:"
          Get-ChildItem -Path "${{ github.workspace }}/publish" -ErrorAction SilentlyContinue
      
      - name: Create ZIP Package
        run: |
          # Debug output
          Write-Host "Workspace path: ${{ github.workspace }}"
          Write-Host "Publish path: ${{ github.workspace }}/publish"
          
          # Create a temporary directory for files to zip
          $tempDir = "${{ github.workspace }}/temp_publish"
          New-Item -ItemType Directory -Path $tempDir
          
          # Copy only WebApplication1 files - corrected path
          Copy-Item "${{ github.workspace }}/publish/WebApplication1" -Destination "$tempDir" -Recurse -ErrorAction Stop
          Copy-Item "${{ github.workspace }}/publish/.deployment" -Destination "$tempDir" -ErrorAction Stop
          
          # Create the zip from the temporary directory
          Compress-Archive -Path "$tempDir/*" -DestinationPath "${{ github.workspace }}/WebApplication1.zip" -Force
          
      - name: Deploy WebApplication1 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          package: ${{ github.workspace }}/WebApplication1.zip
