name: CI/CD for WebApplication1

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Publish WebApplication1
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Restore Dependencies
        run: dotnet restore WebApplication1/WebApplication1.csproj

      - name: Build Application
        run: dotnet build WebApplication1/WebApplication1.csproj --configuration Release --no-restore

      - name: Publish Application
        run: dotnet publish WebApplication1/WebApplication1.csproj --configuration Release --output ${{ github.workspace }}/publish

      - name: Organize Deployment Structure
        shell: pwsh
        run: |
          $deployPath = "${{ github.workspace }}/deploy/WebApplication1"
          if (Test-Path $deployPath) { Remove-Item -Path $deployPath -Recurse -Force }
          New-Item -Path $deployPath -ItemType Directory -Force
          Get-ChildItem -Path "${{ github.workspace }}/publish" | Copy-Item -Destination $deployPath -Recurse -Force
          Write-Host "Final Deployment Structure:"
          Get-ChildItem -Path $deployPath -Recurse

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}/deploy

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}/deploy

      - name: Deploy to Azure Web App (WebApplication1 Folder)
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
          package: ${{ github.workspace }}/deploy/WebApplication1
          clean: false
          additional-deployment-arguments: '-enableRule:DoNotDeleteRule'
