name: Deploy WebApplication1 to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish WebApplication1
        run: dotnet publish WebApplication1/WebApplication1.csproj -c Release -o ${{ github.workspace }}/deploy/temp/site/wwwroot/WebApplication1

      - name: Create ZIP Package
        run: Compress-Archive -Path "${{ github.workspace }}/deploy/temp/*" -DestinationPath "${{ github.workspace }}/WebApplication1.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}/WebApplication1.zip

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}

      - name: Extract ZIP Package
        run: Expand-Archive -Path "${{ github.workspace }}/WebApplication1.zip" -DestinationPath "${{ github.workspace }}/deploy"

      - name: Run Deployment Script
        shell: cmd
        run: |
          cd "${{ github.workspace }}/deploy"
          echo Copying files to WebApplication1 directory...
          if not exist "%CD%\WebApplication1" mkdir "%CD%\WebApplication1"
          xcopy /Y /E /I "%CD%\site\wwwroot\WebApplication1" "%CD%\WebApplication1\"
          if %ERRORLEVEL% NEQ 0 (
            echo An error has occurred during web site deployment.
            exit /b 1
          )
          echo Deployment Successful.

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Stop Azure Web App
        run: az webapp stop --name Git-webapp --resource-group Git-grp
        continue-on-error: true # Avoid failure if already stopped

      - name: Deploy WebApplication1 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          package: ${{ github.workspace }}/deploy/WebApplication1

      - name: Start Azure Web App
        run: az webapp start --name Git-webapp --resource-group Git-grp
