name: Deploy WebApplication1 to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: Install Web Deploy
        run: |
          Invoke-WebRequest -Uri 'https://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi' -OutFile 'WebDeploy_amd64_en-US.msi'
          Start-Process msiexec.exe -Wait -ArgumentList '/I WebDeploy_amd64_en-US.msi /quiet ADDLOCAL=ALL'
          
      - name: Publish WebApplication1
        run: dotnet publish WebApplication1/WebApplication1.csproj -c Release -o "${{ github.workspace }}/publish/WebApplication1"
          
      - name: Create ZIP Package
        run: Compress-Archive -Path "${{ github.workspace }}/publish/WebApplication1/*" -DestinationPath "${{ github.workspace }}/WebApplication1.zip"
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}/WebApplication1.zip

  deploy:
    name: Deploy to Azure Web App
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}
          
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Get Web App Publish Profile
        id: publishprofile
        shell: pwsh
        run: |
          $profile = az webapp deployment list-publishing-profiles --name Git-webapp --resource-group Git-grp --query "[?publishMethod=='MSDeploy']" | ConvertFrom-Json
          $publishUrl = $profile[0].publishUrl
          $username = $profile[0].userName
          $password = $profile[0].userPWD
          
          echo "::add-mask::$password"
          echo "AZURE_PUBLISH_USERNAME=$username" >> $env:GITHUB_ENV
          echo "AZURE_PUBLISH_PASSWORD=$password" >> $env:GITHUB_ENV
          echo "PUBLISH_URL=$publishUrl" >> $env:GITHUB_ENV
          
      - name: Debug Deployment Command
        run: |
          $command = "msdeploy.exe -verb:sync -source:package='${{ github.workspace }}/WebApplication1.zip' -dest:auto,ComputerName='$computerName',AuthType=Basic -setParam:name='IIS Web Application Name',value='Git-webapp/WebApplication1' -enableRule:AppOffline -skip:objectName='filePath',absolutePath='\\WebApplication2\\.*' -enableRule:DoNotDeleteRule -retryAttempts=6 -retryInterval=10000"
          Write-Host "Full Command: $command"
          
      - name: Deploy WebApplication1 to Azure Web App
        shell: pwsh
        run: |
          $publishUrl = $env:PUBLISH_URL
          $username = $env:AZURE_PUBLISH_USERNAME
          $password = $env:AZURE_PUBLISH_PASSWORD
          
          $computerName = "https://$username`:$password@$publishUrl/msdeploy.axd?site=Git-webapp"
          
          Write-Host "Deploy Command: msdeploy.exe -verb:sync -source:package='${{ github.workspace }}/WebApplication1.zip' -dest:auto,ComputerName='$computerName',AuthType=Basic -setParam:name='IIS Web Application Name',value='Git-webapp/WebApplication1' -enableRule:AppOffline -skip:objectName='filePath',absolutePath='\\WebApplication2\\.*' -enableRule:DoNotDeleteRule -retryAttempts=6 -retryInterval=10000"
          
          & 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe' `
            -verb:sync `
            -source:package="${{ github.workspace }}/WebApplication1.zip" `
            -dest:auto,ComputerName=$computerName,AuthType=Basic `
            -setParam:name="IIS Web Application Name",value="Git-webapp/WebApplication1" `
            -enableRule:AppOffline `
            -skip:objectName="filePath",absolutePath="\\WebApplication2\\.*" `
            -enableRule:DoNotDeleteRule `
            -retryAttempts:6 `
            -retryInterval:10000
