name: Deploy WebApplication1 to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Publish WebApplication1
        run: |
          # Show current directory and contents
          Write-Host "Current directory:"
          Get-Location
          Write-Host "Directory contents:"
          Get-ChildItem
          
          # Publish the application
          dotnet publish WebApplication1/WebApplication1.csproj -c Release -o "${{ github.workspace }}/publish"
          
          # Verify publish output
          Write-Host "Published files:"
          Get-ChildItem "${{ github.workspace }}/publish"

      - name: Add deployment config
        run: |
          Add-Content -Path "${{ github.workspace }}/publish/.deployment" -Value @"
          [config]
          SCM_DO_BUILD_DURING_DEPLOYMENT=true
          WEBSITE_RUN_FROM_PACKAGE=0
          "@

      - name: Create ZIP Package
        run: |
          # Create zip directly from publish folder
          Compress-Archive -Path "${{ github.workspace }}/publish/*" -DestinationPath "${{ github.workspace }}/WebApplication1.zip" -Force
          
          # Verify zip file exists
          Get-Item "${{ github.workspace }}/WebApplication1.zip"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}/WebApplication1.zip
          retention-days: 1

  deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WebApplication1
          path: ${{ github.workspace }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy WebApplication1 to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Git-webapp'
          package: ${{ github.workspace }}/WebApplication1.zip
