name: Build and Deploy ASP.NET Core

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: Git-webapp
  DOTNET_VERSION: '6.0.x'
  PUBLISH_PATH: './publish/WebApplication1'

jobs:
  build:
    name: Build and Publish
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish WebApplication1
      run: |
        dotnet publish **/WebApplication1.csproj \
          --configuration Release \
          --output ${{ env.PUBLISH_PATH }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.PUBLISH_PATH }}

  deploy:
    name: Deploy to Azure
    runs-on: windows-latest
    needs: build
    environment: Production

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: webapp

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ./webapp
        virtual-application: 'WebApplication1'
        app-offline: true
        clean: true
        start-up-command: 'dotnet WebApplication1.dll'
